
# SEO settings
title: Technology Should Be Simple
stylished_title: Technology Should Be <span>Simple</span>
description: "Simple Is Better."
keywords: "technology, web, coding, software, business, small businss"
url: https://rivik-media.github.io
baseurl: ""

# google_analytics: UA-50842645-1
# disqus_shortname: "codinfox"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 5
paginate_path: "/page/:num/"
comments: true

#source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Codinfox
  thumb    : https://en.gravatar.com/userimage/42626876/ff31b74f207c61cc9d2d1d9196fd0080.jpg?size=120
  email    : li.zhihao@outlook.com
  url      : http://codinfox.github.io
  github   : http://github.com/codinfox
  twitter  : http://twitter.com/nandomoreirame
  facebook : http://facebook.com/fernando.dev
# linkedin : http://linkedin.com/in/lizhihao

# social settings
# og_locale: "pt_BR"
# twitter_card: "summary_large_image"
twitter_site: "@swoicik"

project:
    repo: https://github.com/rivik-media/rivik-media.github.io 
    name: Rivik Dev
    author: swoicik

gems:
  - jekyll-paginate

