
# SEO settings
title: Technology Should Be Simple
stylished_title: <span>Technology</span> Should Be Simple
description: "Simple Is Better."
keywords: "technology, web, coding, software, business, small businss"
url: https://technologyshouldbesimple.com
baseurl: ""

# google_analytics: UA-50842645-1
# disqus_shortname: "codinfox"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 5
paginate_path: "/page/:num/"
comments: true

#source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : swoicik
  thumb    : 
  email    : hello@rivikmedia.com
  url      : https://rivikmedia.com
  github   : https://github.com/rivik-media
# twitter  : https://twitter.com/rivikmedia
  facebook : 
# linkedin : 

# social settings
# og_locale: "pt_BR"
# twitter_card: "summary_large_image"
twitter_site: "@swoicik"

project:
    repo: https://github.com/rivik-media/technologyshouldbesimple
    name: technologyshouldbesimple
    author: swoicik

gems:
  - jekyll-paginate

