# Site/SEO settings
email: hello@rivikmedia.com
baseurl: " "
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:title/
google_analytics: 

name: Rivik Media
title: Rivik Simple
description: >
  Based on the Barber theme for Jekyll built by Thomas Vaeth for Samesies.
url: http://rivik.co
twitter_username: rivikmedia
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/rivikmedia
  - name: github
    url: https://github.com/rivik-media

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: 

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Stephen Woicik
    bio: Stephen is the President and Co-Founder of Rivik Media. 
    url: http://swoicik.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
