
# SEO settings
title: Rivik Media
description: "Simple Is Better"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: "https://rivik-media.github.io"
baseurl: "/"
# baseurl: null

google_analytics: 
repo: http://github.com/nandomoreirame/simplest

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Fernando Moreira
  job      : Frontend Engineer
  bio      : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb    : /images/author.jpg
  email    : nandomoreira.me@gmail.com
  url      : http://nandomoreira.me
  github   : http://github.com/nandomoreirame
  twitter  : http://twitter.com/nandomoreirame
  facebook : http://facebook.com/fernando.dev
  linkedin : http://linkedin.com/in/nandomoreirame

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
